# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [4]:
res = s.split()
print(res)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [11]:
arr_0 = np.zeros(10, dtype = 'int')
print(arr_0)

[0 0 0 0 0 0 0 0 0 0]


In [12]:
arr_5 = np.ones(10, dtype = 'int')*5
print(arr_5)

[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [13]:
Even = np.arange(20,36,2)
print(Even)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
Matrix = np.arange(0,9).reshape(3,3)
print(Matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
r = np.concatenate((a,b))
print(r)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [16]:
import pandas as pd
import numpy as np
Temp = np.arange(0,6).reshape(3,2)
df = pd.DataFrame(Temp)
print(df)

   0  1
0  0  1
1  2  3
2  4  5


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [21]:
import datetime as dt
import pandas as pd
start_date = dt.date(2023,1,1)
end_date = dt.date(2023,2,10)
tempr = pd.date_range(start_date,end_date)
result = []
for i in tempr.strftime("%b %d, %Y"):
  result.append(i)
s = pd.Series(result)
print(s)

0     Jan 01, 2023
1     Jan 02, 2023
2     Jan 03, 2023
3     Jan 04, 2023
4     Jan 05, 2023
5     Jan 06, 2023
6     Jan 07, 2023
7     Jan 08, 2023
8     Jan 09, 2023
9     Jan 10, 2023
10    Jan 11, 2023
11    Jan 12, 2023
12    Jan 13, 2023
13    Jan 14, 2023
14    Jan 15, 2023
15    Jan 16, 2023
16    Jan 17, 2023
17    Jan 18, 2023
18    Jan 19, 2023
19    Jan 20, 2023
20    Jan 21, 2023
21    Jan 22, 2023
22    Jan 23, 2023
23    Jan 24, 2023
24    Jan 25, 2023
25    Jan 26, 2023
26    Jan 27, 2023
27    Jan 28, 2023
28    Jan 29, 2023
29    Jan 30, 2023
30    Jan 31, 2023
31    Feb 01, 2023
32    Feb 02, 2023
33    Feb 03, 2023
34    Feb 04, 2023
35    Feb 05, 2023
36    Feb 06, 2023
37    Feb 07, 2023
38    Feb 08, 2023
39    Feb 09, 2023
40    Feb 10, 2023
dtype: object


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
df = pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
